databases:
  - name: helpjuice_search
    databaseName: helpjuice_search
    user: helpjuice_search_user
    plan: free

services:
  - type: web
    name: helpjuice-search-backend
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjuice_search
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default