default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: helpjuice_search_back_end_development

test:
  <<: *default
  database: helpjuice_search_back_end_test

production:
  <<: *default
  database: helpjuice_search_back_end_production
  username: helpjuice_search_back_end
  password: <%= ENV["HELPJUICE_SEARCH_BACK_END_DATABASE_PASSWORD"] %>
